pom.xml, src/main/java/com/danielagapov/spawn/Controllers/TestController.java, src/main/java/com/danielagapov/spawn/Models/Event.java, src/main/java/com/danielagapov/spawn/Models/User.java, src/main/resources/application.properties
- Made very basic model classes, marked with `@Entity` to work with JPA (Java Persistence API) -> to map these easily to database entities. 
- Gave them both primary keys of just regular `id` variables
- Replaced old `User` class with proper entity `User` class (model)
=> Models: Event and User

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UserNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UserSaveException.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/IUserService.java, src/main/java/com/danielagapov/spawn/Services/UserService.java
Created `User` endpoint, service, repository, and exceptions.
=> User endpoint, service, repository, and exceptions

src/main/java/com/danielagapov/spawn/Controllers/TestController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UserExceptionHandler.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UsersNotFoundException.java, src/main/java/com/danielagapov/spawn/Models/MockUser.java, src/main/java/com/danielagapov/spawn/Models/User.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/IUserService.java, src/main/java/com/danielagapov/spawn/Services/UserService.java
- HTTP responses for custom exceptiosn
- Moved existing `User` class into `MockUser`
- Adjusted mock endpoints (and created new ones)
- Started groundwork for `getUsersByTagId`, which might be adjusted later on
=> User: HTTP responses for custom exceptions + organized `MockUser`

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BaseExceptionHandler.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BaseNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BaseSaveException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BasesNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UserNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UserSaveException.java, src/main/java/com/danielagapov/spawn/Exceptions/User/UsersNotFoundException.java, src/main/java/com/danielagapov/spawn/Repositories/IEventRepository.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Event: controller + service (w/ interface) + repository
- Turned `User` exceptions to `Base` ones
=> Event workflow + Turning Exceptions Generic

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
An events endpoint for getting events by user id
=> GET /events/user/{id}

entity-relationship-diagram.dbml
Added EventTag to allow a user to see the tags they have applied on the events that they have created
Resolves #30
=> Updated ERD, fixed version

pom.xml, src/main/java/com/danielagapov/spawn/Models/ChatMessage/ChatMessage.java, src/main/java/com/danielagapov/spawn/Models/Event/Event.java, src/main/java/com/danielagapov/spawn/Models/FriendTag/FriendTag.java, src/main/java/com/danielagapov/spawn/Models/User/User.java
=> Proper date/time data types + Using `lombok` library to remove boilerplate: getters, setters, & constructors

.gitignore, pom.xml, src/main/java/com/danielagapov/spawn/SpawnApplication.java, src/main/resources/application.properties
Using .env to set environment variables so that they aren't hardcoded into the app, allowing us to test connections on railway using this repository. Railway connections are also implemented, backend is now hosted online
Resolves #43 
Resolves #44
=> Updated configurations to use .env

src/main/java/com/danielagapov/spawn/Controllers/UserController.java
endpoint for GET users by friend tag
=> GET /users/friendtag/{tag}

src/main/java/com/danielagapov/spawn/SpawnApplication.java, src/main/resources/README.md, src/main/resources/application.properties
- wrapped environment variable code in try catch blocks to detect unset environment variables for debugging purposes
- updated mysql setup instructions to reflect @evannawfal 's environment variable changes
- updated environment variable names for consistency
=> improved clarity for mysql database related areas

pom.xml, src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java, src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/DTOs/ChatMessageLikesDTO.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BaseDeleteException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BasesNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/EntityAlreadyExistsException.java, src/main/java/com/danielagapov/spawn/Mappers/ChatMessageLikesMapper.java, src/main/java/com/danielagapov/spawn/Repositories/IChatMessageLikesRepository.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/main/java/com/danielagapov/spawn/SpawnApplication.java, src/main/resources/README.md, src/main/resources/application.properties, src/test/java/com/danielagapov/spawn/ChatMessageTests/ChatMessageLikesTest.java
Implemented endpoints, service methods, and tests to:
- Create a chatMessageLike
- Delete a chatMessageLike
- Get a list of UserDTOs of people who liked a given comment
This PR also contains changes from the db-models PR but I accidentally branched from that one when I made these changes (oops)
Resolves #43 
Resolves #44
=> Chatmessage likes features

src/main/java/com/danielagapov/spawn/Enums/EntityType.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/BasesNotFoundException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/EntityAlreadyExistsException.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java
- Created `EntityType` to use as an enum, rather than passing in the type as a string to errors.
=> Entity type for errors

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/FriendRequestDTO.java, src/main/java/com/danielagapov/spawn/Mappers/FriendRequestMapper.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
I did this without the use of a DTO and instead, this returns a friend request directly. I didn't think a DTO would be necessary considering the simplicity of the FriendRequests model, but let me know if that should change!
=> Create/Save a new Friend Request

src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java, src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- Added identical controller DELETE endpoints to all 4, with HTTP status codes for various possible errors
- Added identical service class methods to delete these, with error-handling
Resolves some endpoints in #24
=> Deletion Endpoints w/ Appropriate HTTP Status Codes For Errors

src/main/java/com/danielagapov/spawn/Exceptions/Base/ApplicationException.java, src/main/java/com/danielagapov/spawn/Exceptions/Base/DatabaseException.java, src/main/java/com/danielagapov/spawn/Repositories/IUserFriendTagMappingRepository.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Added the functionality for getting users by friend tag to UserService.
=> Get Users by Friend Tag ID

src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java
Fixed BasesNotFoundException -> BaseNotFoundException
=> Adjusted imports for ChatMessageController

src/main/java/com/danielagapov/spawn/Repositories/IFriendTagRepository.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java
Fixed up newly pushed code to fix the DB crashing during building/deployment. 
I also added more environment variables on railway to accommodate the variable name changes to the mysql username and password in the SpawnApplication.java file done here:
https://github.com/Daggerpov/Spawn-App-Back-End/commit/fcd02f02f300bc062cfa35f4f69ffbd0a09f172f
=> Debugging to get DB back online

src/main/java/com/danielagapov/spawn/Models/ChatMessageLikes.java, src/main/java/com/danielagapov/spawn/Models/CompositeKeys/ChatMessageLikesId.java, src/main/java/com/danielagapov/spawn/Models/CompositeKeys/EventInvitedId.java, src/main/java/com/danielagapov/spawn/Models/CompositeKeys/EventParticipantsId.java, src/main/java/com/danielagapov/spawn/Models/EventInvited.java, src/main/java/com/danielagapov/spawn/Models/EventParticipants.java
Created composite key classes, to then use in place of generated ones in our join table models
=> Using composite keys instead of generated ones for join tables

src/main/java/com/danielagapov/spawn/Models/FriendTag.java, src/main/java/com/danielagapov/spawn/Models/User.java, src/main/java/com/danielagapov/spawn/Models/UserFriendTag.java
=> added documentation to User, UserFriendTag, and FriendTag models

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/IFriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Just wanted to finish up #24 as discussed on slack. I'll work on implementing the service methods now.
=> wrote stub service methods and established endpoints for #24

src/main/java/com/danielagapov/spawn/DTOs/ChatMessageLikesDTO.java, src/main/java/com/danielagapov/spawn/Mappers/ChatMessageLikesMapper.java, src/main/java/com/danielagapov/spawn/Models/CompositeKeys/ChatMessageLikesId.java
=> Filling in ChatMessageLikesDTO and Mappings

src/test/java/com/danielagapov/spawn/ChatMessageTests/ChatMessageServiceTests.java, src/test/java/com/danielagapov/spawn/EventServiceTests.java, src/test/java/com/danielagapov/spawn/FriendTagServiceTests.java, src/test/java/com/danielagapov/spawn/UserServiceTests.java
#12 
- Using mock dependencies, just like in `ChatMessageLikesTest`
=> Integration Tests for Service Classes

src/main/java/com/danielagapov/spawn/DTOs/FriendTagDTO.java, src/main/java/com/danielagapov/spawn/Mappers/FriendTagMapper.java, src/test/java/com/danielagapov/spawn/FriendTagServiceTests.java
Not sure if the tests were supposed to pass or not, but this doesn't crash during the building stage anymore. Let me know if you want me to rework the fix.
=> FriendTag Constructor Argument Bug - fixed

src/main/java/com/danielagapov/spawn/Mappers/EventMapper.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- Filled in `creator`, `invited`, `participants`, and `chatMessages` for `EventDTO` mapping in `EventMapper.java`
- Adjusted methods in `EventService`
- Created new stub methods in `UserService` & `ChatMessageService` to handle fetching invited & participating users + chat messages by event id
- these should be filled as part of #77
- Created helper method, `getEventDTOS()` in `EventService` to convert a list of `Event` objects to `EventDTO`s
=> Event mapping fix

src/main/java/com/danielagapov/spawn/Controllers/FriendRequestController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Enums/EntityType.java, src/main/java/com/danielagapov/spawn/Repositories/IUserFriendTagRepository.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/IFriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Finished up #83 and #82 as they were closely related, with these completed I can work on #74.
=> Friend user creation

src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java, src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/FullChatMessageDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullFriendTagDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullUserDTO.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java, src/main/java/com/danielagapov/spawn/Services/Location/LocationService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Guessed which fields we wanted to make full. Please feel free to suggest changes and let me know which endpoints I should add. When I have more time I will investigate redundant methods I think that there might be some methods that we'll never end up using that I created with this PR.
=> Creating full dtos

src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java, src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/ChatMessageDTO.java, src/main/java/com/danielagapov/spawn/DTOs/EventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FriendTagDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullChatMessageDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullFriendTagDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FullUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/IChatMessageDTO.java, src/main/java/com/danielagapov/spawn/DTOs/IEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/IFriendTagDTO.java, src/main/java/com/danielagapov/spawn/DTOs/OnboardedUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/UserDTO.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/Location/ILocationService.java, src/main/java/com/danielagapov/spawn/Services/Location/LocationService.java
Fixed production issues. We could probably change the names and update the abstract classes, I was mainly trying to get it up and running ASAP since I broke it.
=> Fixing pr101 merge

src/main/java/com/danielagapov/spawn/Repositories/IFriendRequestsRepository.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ChatMessageServiceTests.java
#78 
Completed:
- getUsersByTagId
- getParticipatingUsersByEventId
- getIncomingFriendRequestsByUserId
- getChatMessagesByEventId
=> Service Methods Implemented

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/FullUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/IOnboardedUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/RecommendedFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/UserDTO.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- Made new DTO, `RecommendedFriendUserDTO` to include a property `int mutualFriendCount`, for front-end usage in UI here (we can display "2 mutual friends" under each recommended user):
- Implemented `getRecommendedFriendsForUserId()`, which returns a list of 3 `RecommendedFriendUserDTO`s, by the most mutual friends
Open to feedback!
=> Implemented `getRecommendedFriendsForUserId()` + Made `RecommendedFriendUserDTO`

src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java
Changed the method of loading the environment variable
=> change env load

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
+ organized `IEventService` methods
=> Get full events Endpoint + Method for full event returning

src/main/java/com/danielagapov/spawn/Controllers/OAuthController.java, src/main/java/com/danielagapov/spawn/Enums/OAuthProvider.java, src/main/java/com/danielagapov/spawn/Mappers/UserMapper.java, src/main/java/com/danielagapov/spawn/Models/UserIdExternalIdMap.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/OAuth/IOAuthService.java, src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java, src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
=> Auth issues

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/DTOs/FullFeedEventDTO.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
The purpose of this PR is to match the Figma, where there are self-created events listed first, followed by events invited to:
=> Feed events mega endpoint

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/FullFriendUserDTO.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Included documentation in code explaining changes. The gist is to provide friend tags for these views:
=> Including associated friend tags from friends endpoint with new DTO

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Services/S3/IS3Service.java, src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java
Added the default profile picture endpoint and have the static var containing the URL string to the default picture in the s3 bucket
=> add default pfp + GET /default-pfp endpoint

src/main/java/com/danielagapov/spawn/Controllers/UserController.java
Should resolve deployment issues
=> Default pfp

src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java, src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Not the best error logging, but is an improvement from no error logging in these methods
Ran formatter on changed files, so it looks like more changes than were actually made.
=> try catching everything not previously covered in user, S3, and OAuth services

src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Made a change to `OAuthService::makeUser` to detect whether a user exists before trying to save the user. This is a temporary fix for now because I think the root of the sign-in issues is somewhere else
=> hopefully resolve duplicate issues

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
=> Updated get events by friend tag

.github/workflows/syntax-check.yml, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
To avoid accidentally pushing code that doesn't compile
=> Syntax check

src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
=> Ordered Feed + Removing Expired Events

src/test/java/com/danielagapov/spawn/ServiceTests/BetaAccessSignUpServiceTests.java, src/test/java/com/danielagapov/spawn/ServiceTests/OAuthServiceTests.java
=> BetaAcessSignUp & OAuth Service Tests Implemented

src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ServiceTests/FriendRequestServiceTests.java
=> Recommend friend bugfix

src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
Fix should be as simple as this (as a temporary solution). See slack for explanation.
=> Full feed event bug fix

src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- New private methods to use from both `getFeedEvents()` and `getFilteredFeedEventsByFriendTagId()`:
- `sortEventsByStartTime()`
- `removeExpiredEvents()`
- Removed logging statements, since events are working on mobile now
=> Made Logic for Events Sorting & Expired Removal Consistent Between Feed & Tag-Filtered

src/main/java/com/danielagapov/spawn/DTOs/BetaAccessSignUpDTO.java, src/main/java/com/danielagapov/spawn/Mappers/BetaAccessSignUpMapper.java, src/main/java/com/danielagapov/spawn/Models/BetaAccessSignUp.java
Added `hasSubscribedToNewsletter` + removed first & last name, Instagram, and additional comments
=> Beta Access Sign Up Property Adjustments

src/main/java/com/danielagapov/spawn/Config/S3Config.java
Sorry I accidentally put this in wrong branch but this should resolve previous issues with S3 service not working
=> fix s3 credentials

src/main/java/com/danielagapov/spawn/Config/S3Config.java, src/main/java/com/danielagapov/spawn/Controllers/UserController.java
I think the bug with s3 is that the environment variables were being fetched incorrectly on railway
=> change how env vars work on railway

src/main/java/com/danielagapov/spawn/Config/S3Config.java
Ignore if the .env does not exist
=> ignore if .env no exist

src/main/java/com/danielagapov/spawn/DTOs/User/AbstractUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FullFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FullUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/RecommendedFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/UserCreationDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/UserDTO.java, src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java
- Moved `username` & `bio` into `AbstractUserDTO`, since all subclasses use it the same way
- Rename `friendIds` -> `friendUserIds`
- Update comments
=> `AbstractUserDTO` added properties

src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java
- GET options of friend tags to add friend to
- POST which friend tags you're adding the friend to
=> Add User To Tags Endpoints + Methods

src/main/java/com/danielagapov/spawn/Models/Event.java
For #210. Most of the work has already been done in #172. 
Added a cascading delete on the Location field of the Event model so that when an Event is deleted, the Location is deleted as well.
=> Cascading Deletes

src/main/java/com/danielagapov/spawn/DTOs/FriendTag/AbstractFriendTagDTO.java
=> updated AbstractFriendTagDTO to fix #209

src/main/java/com/danielagapov/spawn/DTOs/BetaAccessSignUpDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FriendTag/AbstractFriendTagDTO.java
Explicitly using `@JsonProperty` to specify its name in JSON
=> Fix JSON boolean var names `@JsonProperty`

src/main/java/com/danielagapov/spawn/DTOs/Event/FullFeedEventDTO.java, src/main/java/com/danielagapov/spawn/Mappers/EventMapper.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
Per Slack, change `FullFeedEventDTO`s such that `creatorUser`, `participantUsers`, and `invitedUsers` are now `UserDTO`s instead of `FullUserDTO`s
=> Speed up events

src/main/java/com/danielagapov/spawn/Controllers/EventController.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/CleanUnverified/CleanUnverifiedService.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
This small PR contains simple logging statements for `EventController` & `EventService` + a leaner `FullFeedEventDTO` as described in #220.
=> Staging - Event DTO cut-down

src/main/java/com/danielagapov/spawn/DTOs/Event/FullFeedEventDTO.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
=> added isSelfOwned field to FullFeedEventDTO

src/main/java/com/danielagapov/spawn/Controllers/ReportController.java, src/main/java/com/danielagapov/spawn/DTOs/ReportedContentDTO.java, src/main/java/com/danielagapov/spawn/Enums/EntityType.java, src/main/java/com/danielagapov/spawn/Enums/ReportType.java, src/main/java/com/danielagapov/spawn/Enums/ResolutionStatus.java, src/main/java/com/danielagapov/spawn/Models/ReportedContent.java, src/main/java/com/danielagapov/spawn/Repositories/IReportedContentRepository.java, src/main/java/com/danielagapov/spawn/Services/Report/IReportContentService.java, src/main/java/com/danielagapov/spawn/Services/Report/ReportContentService.java
For #174.
This PR contains the implementation of functionality to report content/accounts.
Made the model, service, repository, and controller class for the ReportedContent entity.
Actions to take against reported users (e.g. bans, suspension, warning, etc.) will be implemented in a separate PR.
=> Report content

src/main/java/com/danielagapov/spawn/Controllers/FriendRequestController.java, src/main/java/com/danielagapov/spawn/DTOs/FriendRequest/AbstractFriendRequestDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FriendRequest/CreateFriendRequestDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FriendRequest/FetchFriendRequestDTO.java, src/main/java/com/danielagapov/spawn/Mappers/FriendRequestMapper.java, src/main/java/com/danielagapov/spawn/Services/FriendRequest/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequest/IFriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ServiceTests/FriendRequestServiceTests.java
Renamed FriendRequestDTO to CreateFriendRequestDTO.
Introduced AbstractFriendRequestDTO.
Note: lots of changed files but that's just because of the DTO rename. The main place to review is the `DTOs.FriendRequest` package.
=> Refactor FriendRequestDTOs

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/FriendRequest/FetchFriendRequestDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FriendUser/AbstractFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FriendUser/FullFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FriendUser/PotentialFriendUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/User/FriendUser/RecommendedFriendUserDTO.java, src/main/java/com/danielagapov/spawn/Mappers/FriendUserMapper.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequest/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ServiceTests/FriendRequestServiceTests.java
Like discussed in Slack, added a new `PotentialFriendUserDTO` and refactored `FetchFriendRequestDTO.senderUser` to be of type `PotentialFriendUserDTO`.
Also since the number of `FriendUserDTO`s are growing, I added a new sub-package of `DTOs.User` to encapsulate them: `DTOs.User.FriendUser`.
=> Added PotentialFriendUserDTO

README.md
#234 
Almost done, just need to explain a couple more things in another PR about our code specifically with DTOs and Mappers (I want to use excalidraw for those, like in the prior explanations in our README related to those kinds of things, to fit in).
=> Additional Documentation for Spring Boot & JPA (Java Persistence API) + Hibernate

src/main/java/com/danielagapov/spawn/Controllers/AuthController.java, src/main/java/com/danielagapov/spawn/Enums/EntityType.java, src/main/java/com/danielagapov/spawn/Exceptions/IncorrectProviderException.java, src/main/java/com/danielagapov/spawn/Repositories/IUserIdExternalIdMapRepository.java, src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/OAuth/IOAuthService.java, src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/main/java/com/danielagapov/spawn/Util/ErrorResponse.java
Updated Oauth sign-in so that an error message is sent back when a user tries to log into their account with same email but different provider.
This should also resolve a bug with the sign-in endpoint.
=> Fix sign-in bug and introduce ErrorResponse

src/main/java/com/danielagapov/spawn/DTOs/FriendTag/AbstractFriendTagDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FriendTag/FriendTagDTO.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/test/java/com/danielagapov/spawn/ServiceTests/FriendTagServiceTests.java
Blocked deletion for the Everyone tag.
=> Everyone Tag Deletion Fix

src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
=> Fix add friends to tag endpoint

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Repositories/IEventRepository.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Simple, and addresses issue Shane pointed out with our mobile app on the back-end; will do mobile side now
=> User bio patch endpoint

src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/DTOs/User/UserUpdateDTO.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ServiceTests/UserServiceTests.java
Added username, first name, and last name to the update user endpoint to replace update bio endpoint, per #273
=> User update patch endpoint method extension for more properties

src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
Fix for #270 + a small refactor to the feed events.
=> Refactor feed methods

src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java
Made the Default PFP read-only so it cannot be updated by a user.
=> Default PFP Fix

src/main/java/com/danielagapov/spawn/Controllers/FeedbackSubmissionController.java, src/main/java/com/danielagapov/spawn/DTOs/CreateFeedbackSubmissionDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FeedbackSubmissionDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FetchFeedbackSubmissionDTO.java, src/main/java/com/danielagapov/spawn/Mappers/FeedbackSubmissionMapper.java, src/main/java/com/danielagapov/spawn/Models/FeedbackSubmission.java, src/main/java/com/danielagapov/spawn/Services/FeedbackSubmission/FeedbackSubmissionService.java, src/main/java/com/danielagapov/spawn/Services/FeedbackSubmission/IFeedbackSubmissionService.java, src/test/java/com/danielagapov/spawn/ServiceTests/FeedbackSubmissionServiceTests.java
Made the endpoint the same as with the `make-user` one in `AuthController.java`, accepting the image data as a byte array. 
We discussed on Slack that feedback should take in an image, so I'll make the UI on mobile to go with this endpoint.
=> Feedback Image Support

src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java, src/main/java/com/danielagapov/spawn/Controllers/BetaAccessSignUpController.java, src/main/java/com/danielagapov/spawn/DTOs/BetaAccessSignUpDTO.java, src/main/java/com/danielagapov/spawn/DTOs/CreateFeedbackSubmissionDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FetchFeedbackSubmissionDTO.java, src/main/java/com/danielagapov/spawn/Enums/EntityType.java, src/main/java/com/danielagapov/spawn/Mappers/BetaAccessSignUpMapper.java, src/main/java/com/danielagapov/spawn/Mappers/FeedbackSubmissionMapper.java, src/main/java/com/danielagapov/spawn/Models/BetaAccessSignUp.java, src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/BetaAccessSignUpService.java, src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/IBetaAccessSignUpService.java, src/main/java/com/danielagapov/spawn/Services/FeedbackSubmission/FeedbackSubmissionService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java
- "has been emailed" property for front-end to use, so that for future beta access sign ups, we'll know not to resend to people who have previously been sent an access email
- first & last name for user identification in front-end for feedback
- fixed invalid date issue with submitted at time in DTO
- fix resolution comment not persisting to DB
=> Admin Site: Beta Sign-Up "Has Been Emailed" + Feedback Resolution Fixes

README.md, src/main/java/com/danielagapov/spawn/Config/AdminUserInitializer.java, src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java, src/main/java/com/danielagapov/spawn/Services/UserDetails/UserInfoService.java
- using railway env vars to create admin user in the back-end, that the front-end admin site will connect using
=> Admin user

src/main/java/com/danielagapov/spawn/Config/RedisCacheConfig.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
Added Time to live (TTL) to remove stale cached data. The current time until data expires is 10 minutes, let me know if you have any thoughts on this. Also started to try and fix the cause of that friendtag caching bug.
=> TTL Implemented

USER_LOGGING_IMPLEMENTATION.md, src/main/java/com/danielagapov/spawn/Controllers/UserController.java, src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java, src/main/java/com/danielagapov/spawn/Services/BlockedUser/BlockedUserService.java, src/main/java/com/danielagapov/spawn/Services/FeedbackSubmission/FeedbackSubmissionService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequest/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/PushNotification/NotificationService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/main/java/com/danielagapov/spawn/Utils/LoggingUtils.java, src/test/java/com/danielagapov/spawn/ServiceTests/BlockedUserServiceTests.java, src/test/java/com/danielagapov/spawn/ServiceTests/FeedbackSubmissionServiceTests.java, src/test/java/com/danielagapov/spawn/ServiceTests/FriendRequestServiceTests.java, src/test/java/com/danielagapov/spawn/ServiceTests/UserServiceTests.java
This is to address logs being hard to read, when they involve users, being that we've historically only logged the user id. 
- Also refactored `NotificationService`
- Also Refactored user deletion method to void instead of boolean return type
=> `LoggingUtils` for better user info logging (not just user id)

src/main/java/com/danielagapov/spawn/Config/JWTFilterConfig.java, src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java
Securing endpoints with recent JWT updates to mobile
Don't merge, will point deployment at this branch to test
=> Secure endpoints

src/main/java/com/danielagapov/spawn/DTOs/Event/AbstractEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/EventCreationDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/EventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/FullFeedEventDTO.java, src/main/java/com/danielagapov/spawn/Enums/EventCategory.java, src/main/java/com/danielagapov/spawn/Mappers/EventMapper.java, src/main/java/com/danielagapov/spawn/Models/Event.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
=> Event: Additional Fields for new Event Creation

src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java, src/main/java/com/danielagapov/spawn/Services/BlockedUser/BlockedUserService.java, src/main/java/com/danielagapov/spawn/Services/FeedbackSubmission/FeedbackSubmissionService.java, src/main/java/com/danielagapov/spawn/Services/FriendRequest/FriendRequestService.java, src/main/java/com/danielagapov/spawn/Services/PushNotification/NotificationService.java, src/main/java/com/danielagapov/spawn/Services/Report/Cache/CacheService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/main/java/com/danielagapov/spawn/Util/LoggingUtils.java
=> Move LoggingUtils

src/main/java/com/danielagapov/spawn/DTOs/Event/AbstractEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/EventCreationDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/EventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/FullFeedEventDTO.java, src/main/java/com/danielagapov/spawn/DTOs/Event/ProfileEventDTO.java, src/main/java/com/danielagapov/spawn/Mappers/EventMapper.java, src/main/java/com/danielagapov/spawn/Models/Event.java, src/main/java/com/danielagapov/spawn/Services/Event/EventService.java, src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
This is to make the "Posted 7 hours ago" in the bottom here possible:
Changes have already been made to iOS
=> Add Event `createdAt` Property

src/main/java/com/danielagapov/spawn/Controllers/ActivityController.java, src/main/java/com/danielagapov/spawn/Services/Activity/ActivityService.java, src/main/java/com/danielagapov/spawn/Services/Activity/IActivityService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java, src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java
Added an endpoint to fetch an activity's chat messages by activity id. The purpose of this endpoint is so that an activity's chatroom can be refreshed from mobile.
=> Fetch chat messages by activity id

src/main/java/com/danielagapov/spawn/Controllers/User/ReportController.java, src/main/java/com/danielagapov/spawn/DTOs/BlockedUser/BlockedUserDTO.java, src/main/java/com/danielagapov/spawn/DTOs/CreateReportedContentDTO.java, src/main/java/com/danielagapov/spawn/DTOs/FetchReportedContentDTO.java, src/main/java/com/danielagapov/spawn/Mappers/BlockedUserMapper.java, src/main/java/com/danielagapov/spawn/Services/Report/IReportContentService.java, src/main/java/com/danielagapov/spawn/Services/Report/ReportContentService.java
- split report user dtos into create and fetch
- included extra user info for fetch blocked user, for displaying in Settings -> "Blocked Users" page
=> User Blocking & Reporting: Accommodating Extra Features

src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java
Since names cannot be null, I need to explicitly set it to an intermediate value before saving
=> Bug fix for names

src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java
=> Whitelist login

src/main/java/com/danielagapov/spawn/Controllers/AuthController.java
make new tokens when user updates username
=> Make new tokens

src/main/java/com/danielagapov/spawn/Controllers/AuthController.java, src/main/java/com/danielagapov/spawn/Enums/UserStatus.java, src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java, src/main/java/com/danielagapov/spawn/Services/Auth/IAuthService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/test/java/com/danielagapov/spawn/ServiceTests/OAuthServiceTests.java
=> Quick sign-in return AuthResponseDTO

src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java, src/main/java/com/danielagapov/spawn/Controllers/AuthController.java, src/main/java/com/danielagapov/spawn/DTOs/User/AuthResponseDTO.java, src/main/java/com/danielagapov/spawn/Mappers/UserMapper.java, src/main/java/com/danielagapov/spawn/Models/User/UserInfo.java, src/main/java/com/danielagapov/spawn/Repositories/User/IUserIdExternalIdMapRepository.java, src/main/java/com/danielagapov/spawn/Repositories/User/IUserRepository.java, src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java, src/main/java/com/danielagapov/spawn/Services/Auth/IAuthService.java, src/main/java/com/danielagapov/spawn/Services/Email/EmailService.java, src/main/java/com/danielagapov/spawn/Services/OAuth/IOAuthService.java, src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java, src/main/java/com/danielagapov/spawn/Services/User/IUserService.java, src/main/java/com/danielagapov/spawn/Services/User/UserService.java, src/main/java/com/danielagapov/spawn/Services/UserDetails/UserInfoService.java, src/main/resources/templates/emailVerificationCode.html
Added role-based access to endpoints since we allow for re-login to inactive accounts now
Also switched up email template so verification code is in subject of email for ease of access
=> Continue onboarding
