Daggerpov/Spawn-App-Back-End

- src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java
- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
- src/main/java/com/danielagapov/spawn/Repositories/IEventRepository.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
#59 
Simple PR, just doing what's been done to a few endpoints with http response codes to all of them for consistency, and so the mobile side can error-handle more effectively.
- Also, implemented the following methods in `EventService.java` properly: `getEventsByTagId()` & `getEventsByUserId()`
For our controller classes, I’ve just realized we should be returning 200 status codes (HttpStatus.OK) instead of 404 (HttpStatus.NOT_FOUND), based on this answer: https://stackoverflow.com/a/13367198/13368695.
This doesn’t require any changes to how we’re throwing BaseNotFoundException and BasesNotFoundException in our service class layer, so don’t worry about that. It’s just that from those errors, we need to return a different status code, as I’ll adjust for in my current PR, Controllers: …
> Controllers: Return Proper HTTP Responses

- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/DTOs/FullFeedEventDTO.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java
#105 
Feel free to comment on anything, from naming to logic. I'm open to suggestions. 
- Rename `FullEventDTO` -> `FullFeedEventDTO` to convey purpose on mobile side of loading in feed
- added color hex code property, as per #105 
- Implemented its logic for retrieval in new methods: `getFriendTagColorHexCodeForRequestingUser()` & `getPertainingFriendTagByUserIds()`
- Returned `FullFeedEventDTO` from `invitedEvents` endpoint with same `full` request param as @SeabertYuan used in #100 
- Created helper method `constructDTOFromEntity(Event eventEntity)` for duplicate code fragment
> `FullEventDTO`: including color & `ParticipationStatus` + returning from  new `invitedEvents` endpoint

- src/main/java/com/danielagapov/spawn/Controllers/OAuthController.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/IOAuthService.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java
- src/main/java/com/danielagapov/spawn/Services/S3/IS3Service.java
- src/main/java/com/danielagapov/spawn/Services/S3/S3Service.java
- Documentation
- Changed var names from `id` & `sub` -> `userId` or `externalUserId`
- Code change:
Before:
```
// full path: /api/v1/oauth/sign-in?sub=su
@GetMapping("sign-in?sub=sub")
```
After:
```
// full path: /api/v1/oauth/sign-in?externalUserId=externalUserId
@GetMapping("sign-in")
```
Pretty sure the old path was causing this 404 (should probably return 500 error, not 404):
, given that this is the code behind it:
```
} catch (Exception e) {
return ResponseEntity.internalServerError().body(null);
}
```
> OAuth: Documentation and var name changes

- src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java
- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
- src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java
- src/main/java/com/danielagapov/spawn/Services/ChatMessage/IChatMessageService.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java
- Added `@Request param boolean full` arg to more controller GET endpoints
- Made new helper methods in service classes, `convertXsToFullXs` to help with this, in a more clean way than having separate wrapper methods for each method to call, that are different but accomplish the same thing, like `getFullFeedEventsByUserId` -> instead of that, just keeping the old methods in tact then wrapping them with `convertEventsToFullFeedEvents()` in a more clean way
> `full` args for more methods and controllers

- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/DTOs/EventCreationDTO.java
- src/main/java/com/danielagapov/spawn/Mappers/EventMapper.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
- src/main/java/com/danielagapov/spawn/Services/Location/ILocationService.java
- src/main/java/com/danielagapov/spawn/Services/Location/LocationService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/test/java/com/danielagapov/spawn/EventServiceTests.java
- src/test/java/com/danielagapov/spawn/UserServiceTests.java
Created new post endpoint to accommodate event creation that contains just friend tag ids and a list of invited users. With the friend tag ids & user ids, our back-end should be able to fetch which users the creating user intends to invite.
AI tests are passing, but let me know if anything looks fishy.
Resolves #96
> Eventcreation Endpoint & DTO Implemented

- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Started questioning why we weren't getting recommended friends on the mobile app, and realized it's because if you don't have any friends added, Spawn can't recommend you mutuals. So, this change will populate `recommended-friends`'s response with random users, or fill recommended friends up to 3 with random users if there were < 3 recommended friends from my original algorithm
> Filling recommended friends with random ones if user doesn't already have friends

- src/main/java/com/danielagapov/spawn/Controllers/BetaAccessSignUpController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendRequestController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
- src/main/java/com/danielagapov/spawn/DTOs/BetaAccessSignUpDTO.java
- src/main/java/com/danielagapov/spawn/Mappers/BetaAccessSignUpMapper.java
- src/main/java/com/danielagapov/spawn/Models/BetaAccessSignUp.java
- src/main/java/com/danielagapov/spawn/Repositories/IBetaAccessSignUpRepository.java
- src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/BetaAccessSignUpService.java
- src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/IBetaAccessSignUpService.java
This domain will be used by our site for gathering beta access users, which we'll then invite. Therefore, I've made 3 endpoints to satisfy requirements that would come with these tasks. 
- (POST) Sign Up: upon submitting front-end form
-  [spawn-app-back-end-production.up.railway.app/api/v1/betaAccessSignUp](spawn-app-back-end-production.up.railway.app/api/v1/betaAccessSignUp)
- (GET) All Emails: for the purpose of when we're sending our beta access invites
- [spawn-app-back-end-production.up.railway.app/api/v1/betaAccessSignUp/emails](spawn-app-back-end-production.up.railway.app/api/v1/betaAccessSignUp/emails)
- (GET) All Records: for internal use to see all info from records 
- [spawn-app-back-end-production.up.railway.app/api/v1/betaAccessSignUp](spawn-app-back-end-production.up.railway …
> Beta Access Sign Up Domain

- src/main/java/com/danielagapov/spawn/Repositories/IFriendRequestsRepository.java
- src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java
- src/main/java/com/danielagapov/spawn/Services/FriendRequestService/IFriendRequestService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Adjusted getRecommendedFriendsForUserId in UserService to now:
- Only recommend friends that you have not already sent a request to
- Only recommend friends that you do not have a request from
- Exclude the current user from the list of recommendations
Resolves #151
> Recommend friend bugfix

- src/main/java/com/danielagapov/spawn/Controllers/FriendRequestController.java
- src/main/java/com/danielagapov/spawn/Enums/FriendRequestAction.java
- src/main/java/com/danielagapov/spawn/Services/FriendRequestService/FriendRequestService.java
- more consise endpoints
- consolidated accept & reject endpoints into one with a new `@RequestParam` of new enum type `FriendRequestAction`
- removed unused `userId` path variable arguments from them
- removed prefix `/users/` in URL
- try-catching in `acceptFriendRequest()` (cherry-picked this commit into `main` already)
To note, this does not address the bug in #154
> Reworked friend req endpoints

- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
- src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java
- src/main/java/com/danielagapov/spawn/Services/User/IUserService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/ChatMessageServiceTests.java
- src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
- src/test/java/com/danielagapov/spawn/ServiceTests/OAuthServiceTests.java
- Added `visitedUsers` to these methods:
- `UserService::getFullUserByUser()`
- `UserService::convertUsersToFullUsers()`
All other changes simply supply `new HashSet<>()` for these arguments to start off the recursion empty, so there's no real need to review those.
Explanation:
- provided `visitedUsers` argument to pass between these methods, such that they don't re-visit the same user (similar to Leetcodes involving DFS, like in Course Schedule II where you have to detect cycles--except now, we're bullet-proofing against cycles)
- This implementation ensures we can keep the `FullUserDTO` the same, with having embedded friends' full DTOs, instead of having to convert these down to base `UserDTO`s--which could've also fixed this issue
- This was done to ensure mobile wouldn't be affected …
> Fix circular dependency between `getFullUserByUser()` and `convertUsersToFullUsers()` + `getRecommendedFriends` excluding existing friends

- src/main/java/com/danielagapov/spawn/Models/CompositeKeys/ChatMessageLikesId.java
- src/main/java/com/danielagapov/spawn/Models/CompositeKeys/EventUsersId.java
- src/main/java/com/danielagapov/spawn/Repositories/IEventUserRepository.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
- Main bug fix: we were using `UUID`s to find `EventUser` entities, while they should really be identified using the composite key, `EventUsersId`
- Fixed composite key ids by implementing `.equals()` and `.hashCode()` methods
- Simplified methods in `EventService` relating to participation, using the proper composite ids
- Adjusted tests
> Event User Domain Fixes

- src/main/java/com/danielagapov/spawn/Controllers/OAuthController.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java
For #180.
For apple oauth, the only necessary change is to remove the requirement for email in the sign-in endpoint and only try checking if a user exists by email, when email is not null.
For the make-user endpoint, there is no longer any reason for the `externalId ` argument to not be required, since email+pass authentication will be done at a separate endpoint. Additionally, there is no reason for the `provider` argument to not be required; it should always be one of "google" or "apple". This will be a breaking change if not already provided from Mobile.
> change requirements for make-user endpoint

- src/main/java/com/danielagapov/spawn/Controllers/AuthController.java
I had a space in a custom header name ("Refresh Token") that I think might have been causing issues.
> Change Custom Header name

- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/OAuthServiceTests.java
Returning modified list, instead of modifying in-place, since that caused a bug:
> Bug fix expired events

- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
saveFriendToUser now disallows situations where users could unintentionally add themselves to their own "Everyone" tag through the saveFriendToUser method.
> SaveFriendToUser Fix

- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
The issue with fetching events was that `EventService::sortEventsByStartTime` was trying to sort (and thereby modify) an immutable list returned by `EventService::removeExpiredEvents`.
For reference, the following methods return immutable collections:
- `stream().collect(Collectors.toUnmodifiableList())`
- `stream().collect(Collectors.toList())`
- `stream().toList()`
- `List.of()`
- `Arrays.asList()`
> Fix event issue

- src/main/java/com/danielagapov/spawn/Exceptions/Base/BaseNotFoundException.java
- src/main/java/com/danielagapov/spawn/Repositories/IFriendTagRepository.java
- src/main/java/com/danielagapov/spawn/Repositories/IUserRepository.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/IFriendTagService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/main/java/com/danielagapov/spawn/Services/UserDetails/UserInfoService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/EventServiceTests.java
- Wrapped singular entity DB queries with `Optional<>`
- New `BaseNotFoundException(EntityType et, String identifier, String identifierType)` exception, to specify `identifierType`, instead of being confined to `username` only (we can now use email or something else)
- `UserService:: saveFriendToUser()` bug should be fixed (in Slack, #testing-qa)
- `FriendTagService::getPertainingFriendTagByUserIds()`
> 2 Bug Fixes + Optionals for DB Queries

- src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java
- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendRequestController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java
- src/main/java/com/danielagapov/spawn/Controllers/LocationController.java
- src/main/java/com/danielagapov/spawn/Controllers/ReportController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
Could prevent downstream errors to do with null id params in service methods, or to repo method calls. 
Just bullet-proofing our controllers, to not let null ids through to service classes. 
In `EventController`, I removed unused:
- endpoint (with path     // full path: /api/v1/events/{id}?full=full&requestingUserId=requestingUserId)
- logger
> Returning 400 errors for missing id params in endpoints

- src/main/java/com/danielagapov/spawn/Controllers/AuthController.java
- src/main/java/com/danielagapov/spawn/Mappers/UserMapper.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/IOAuthService.java
- src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/OAuthServiceTests.java
As discussed on Slack, refactored the endpoints `AuthController::makeUser` and `AuthController::signIn` to return `BaseUserDTO`s instead of `FullUserDTO`s. Also updated the tests accordingly.
> OAuth BaseUserDTO refactor

- src/main/java/com/danielagapov/spawn/Controllers/ChatMessageController.java
- src/main/java/com/danielagapov/spawn/Controllers/EventController.java
- src/main/java/com/danielagapov/spawn/Controllers/FriendTagController.java
- src/main/java/com/danielagapov/spawn/Controllers/LocationController.java
- src/main/java/com/danielagapov/spawn/Controllers/ReportController.java
- src/main/java/com/danielagapov/spawn/Controllers/UserController.java
- Removed all mock endpoints
- Documented unused endpoints with `@Deprecated`
- If those endpoints will soon be used by mobile, as documented in [this mobile issue](https://github.com/Daggerpov/Spawn-App-iOS-SwiftUI/issues/142), then they mention that
> Endpoint Mobile Usage Documentation

- src/main/java/com/danielagapov/spawn/DTOs/FriendRequest/FetchFriendRequestDTO.java
- src/main/java/com/danielagapov/spawn/Mappers/FetchFriendRequestMapper.java
- src/main/java/com/danielagapov/spawn/Services/FriendRequest/FriendRequestService.java
- src/main/java/com/danielagapov/spawn/Services/User/IUserService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
Created this separate PR so we don't have to merge #260 before this, since this is more important--likely fixes the bug in #testing-qa
- Replaced `.toDTOList()` with a direct `.map()` call from service class, to avoid having to inject a dependency (`UserService`) into the mapper class
> Cherry-picked mutual friend count addition

- src/main/java/com/danielagapov/spawn/Repositories/IFriendTagRepository.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/FriendTagServiceTests.java
- src/test/java/com/danielagapov/spawn/ServiceTests/UserServiceTests.java
I believe this should fix the current bug in #testing-qa by making a db query return optional, instead of unwrapping a null value for friend ids
> Fix current bug with optional db query

- src/main/java/com/danielagapov/spawn/Repositories/IEventRepository.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/Event/IEventService.java
Per Slack: "it seems the bug is due to the way events are fetched through `EventController::getEventsByFriendTag()`. Currently, `getEventsByFriendTag()` is getting events that a user's friends has created, when it should be events that a user has been invited to."
With this PR, we are now getting events that a user has been invited by all their friends who belong to the specified friend tag. This logic is done at the database level with a single query (`IEventRepository::getEventsInvitedToWithFriendTagId`).
> Events by Friend Tag bug fix

- src/main/java/com/danielagapov/spawn/Events/NewCommentNotificationEvent.java
- src/main/java/com/danielagapov/spawn/Services/PushNotification/NotificationService.java
- Only sending notifications if user has turned on that preference through their device
- Adjusted chat message sending according to Shane on Slack:
"Backend noti bug: I got a notification from commenting on my own Event when I should receive 0"
> Notifications: Preference-Based Sending + Bug Fixes

- src/main/java/com/danielagapov/spawn/Repositories/IChatMessageRepository.java
- src/main/java/com/danielagapov/spawn/Services/ChatMessage/ChatMessageService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/ChatMessageServiceTests.java
Previously chat messages were unordered when returned by any event endpoint. Now they are ordered from newest -> oldest.
So, in the app, when you click on an event, new chat messages will be on top, older chat messages are at the bottom.
Used DB level sorting
> Add chat message ordering

- pom.xml
- src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/BetaAccessSignUpService.java
- src/main/java/com/danielagapov/spawn/Services/BlockedUser/BlockedUserService.java
- src/main/java/com/danielagapov/spawn/Services/Event/EventService.java
- src/main/java/com/danielagapov/spawn/Services/FriendTag/FriendTagService.java
- src/main/java/com/danielagapov/spawn/SpawnApplication.java
- src/main/resources/application.properties
Integrated Redis caching into `EventService` methods to improve performance and reduce database load.
- **Added `@Cacheable`** to:
- `getEventById`, `getFullEventById`
- `getEventsByOwnerId`, `getEventsByFriendTagId`
- `getEventsInvitedTo`, `getFullEventsInvitedTo`
- `getFeedEvents`, `getFilteredFeedEventsByFriendTagId`
- **Added `@CacheEvict`** to:
- `saveEvent`, `createEvent`, `replaceEvent`, `deleteEventById`
- `inviteUser`, `toggleParticipation`
- `save/replace/deleteFriendTag`
- `save/removeUserTo/fromFriendTag`
- **Redis Config**:
- Set `REDIS_HOST`, `REDIS_PORT`, `REDIS_PASSWORD` as environment variables (shared only with backend)
- Setup Redis on railway
- **TODO**:
- Finish implementing cache evicts on methods that affect eventservice (like chatmessages)
- Add caching to other …
> Redis Caching - Events

- src/main/java/com/danielagapov/spawn/Models/User.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/main/java/com/danielagapov/spawn/Services/UserSearch/UserSearchService.java
Small PR for the existing search endpoint to include results retrieved from the new fuzzy search implementation.
> Change getRecommendedFriendsBySearch

- pom.xml
- src/main/java/com/danielagapov/spawn/Config/FCMInitializer.java
- src/main/java/com/danielagapov/spawn/Config/SecurityConfig.java
- src/main/java/com/danielagapov/spawn/Controllers/NotificationController.java
- src/main/java/com/danielagapov/spawn/Services/PushNotification/FCMService.java
- src/main/java/com/danielagapov/spawn/Services/PushNotification/NotificationService.java
- src/main/java/com/danielagapov/spawn/Services/PushNotification/NotificationVO.java
- src/main/resources/application.properties
Backend FCM integration.
The new `FCMService` class is used solely for sending a notification to the device (technically to the remote FCM service, then the device). FCM handles whether the notification should be sent to an iOS or an Android device, so we no longer need the `APNStrategy` and `AndroidStrategy` classes since our backend can treat sending a notification the same, regardless of the user's actual device type. This will be removed in a future PR once it is completely confirmed that notifications are working correctly.
> FCM Integration

- src/main/java/com/danielagapov/spawn/Config/JWTFilterConfig.java
- src/main/java/com/danielagapov/spawn/Controllers/User/AuthController.java
- src/main/java/com/danielagapov/spawn/Controllers/User/UserController.java
- src/main/java/com/danielagapov/spawn/Services/Auth/AuthService.java
- src/main/java/com/danielagapov/spawn/Services/BetaAccessSignUp/BetaAccessSignUpService.java
- src/main/java/com/danielagapov/spawn/Services/User/IUserService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/test/java/com/danielagapov/spawn/ServiceTests/BetaAccessSignUpServiceTests.java
- src/test/java/com/danielagapov/spawn/ServiceTests/UserServiceTests.java
- Kept logs for features in development or for ones that haven't been tested yet, like email/pass user registration, change password, etc.
- Cleaned up ones that were clogging the Railway logs, though, like for tokens. 
- Notify team by email upon beta access sign up, since we haven't sent a follow-up invite since March but should, since new sign ups have been made
- Move logic of getting DTO properties from controller -> service layer for `UserService::updateUser()`
> Notify Team about Beta Sign Ups + Clean Logs

- src/main/java/com/danielagapov/spawn/Controllers/User/UserController.java
- src/main/java/com/danielagapov/spawn/DTOs/User/AbstractUserDTO.java
- src/main/java/com/danielagapov/spawn/DTOs/User/BaseUserDTO.java
- src/main/java/com/danielagapov/spawn/DTOs/User/RecentlySpawnedUserDTO.java
- src/main/java/com/danielagapov/spawn/DTOs/UserIdEventTimeDTO.java
- src/main/java/com/danielagapov/spawn/Repositories/IEventUserRepository.java
- src/main/java/com/danielagapov/spawn/Repositories/IUserFriendTagRepository.java
- src/main/java/com/danielagapov/spawn/Services/Report/Cache/CacheService.java
- src/main/java/com/danielagapov/spawn/Services/User/IUserService.java
- src/main/java/com/danielagapov/spawn/Services/User/UserService.java
- src/main/java/com/danielagapov/spawn/Services/UserSearch/IUserSearchService.java
- src/main/java/com/danielagapov/spawn/Services/UserSearch/UserSearchService.java
- src/main/java/com/danielagapov/spawn/SpawnApplication.java
- src/test/java/com/danielagapov/spawn/ServiceTests/UserSearchServiceTests.java
- src/test/java/com/danielagapov/spawn/ServiceTests/UserServiceTests.java
Implementation for "recently spawned with users". The intended logic for this functionality involves fetching the recent events (currently capped at 10) a user has participated in and returning all other users who have also participated in any of those events and are not friends of the requesting user.
> Recently Spawned With Users

- src/main/java/com/danielagapov/spawn/Services/OAuth/OAuthService.java
This was to fix the following issue:
If I don't complete the account creation process, say I sign in through google, but don't fully make the user, don't save that user in the database, or at least don't stop someone from completing the account creation process. 
For example, like what I was saying, if someone clicks "continue with google" -> signs in -> doesn't complete name, username, etc. -> closes app -> continues with google again to create account again -> don't tell them the account already exists.
> Only treating active users as real ones for auth
